name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Determine changed paths
        id: changes
        run: |
          echo "FRONTEND_CHANGED=false" >> $GITHUB_ENV
          echo "BACKEND_CHANGED=false" >> $GITHUB_ENV

          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/'; then
            echo "FRONTEND_CHANGED=true" >> $GITHUB_ENV
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^backend/'; then
            echo "BACKEND_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Deploy to server
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
            cd ${{ secrets.REMOTE_PATH }}

            echo "Frontend changed: $FRONTEND_CHANGED"
            echo "Backend changed: $BACKEND_CHANGED"

            if [ "$FRONTEND_CHANGED" = "true" ]; then
              echo "Rebuilding frontend..."
              docker compose build frontend
              docker compose up -d frontend
            fi

            if [ "$BACKEND_CHANGED" = "true" ]; then
              echo "Rebuilding backend..."
              docker compose build backend
              docker compose up -d backend
            fi
          EOF
